remote_theme: DottleWither/cayman
title: "flowers"
description: "heaven and earth"
markdown: kramdown
defaults:
  -
    scope:
      path: "post"
    values:
      layout: "post"
      mathjax: true
      category: "post"
